services:

  app:
    image: liatfoto_app
    container_name: liatfoto_app
    restart: unless-stopped
    working_dir: /var/www
    network_mode: "host"
    volumes:
      - .:/var/www
      - /mnt/foto:/mnt/foto
      - /mnt/data-internal:/mnt/data-internal

  nginx:
    image: nginx:alpine
    container_name: liatfoto_nginx
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /mnt/foto:/mnt/foto
      - /mnt/data-internal:/mnt/data-internal

  db:
    image: postgres:15
    container_name: liatfoto_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: liatfoto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: edp123
    ports:
      - "6432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 